[package]
name = "grim-vm"
description = "UnrealScript virtual machine: bytecode interpreter, states, latent functions and natives"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
grim-fs.workspace = true
grim-package.workspace = true
grim-assets.workspace = true
grim-object.workspace = true
grim-save.workspace = true
grim-world.workspace = true
grim-audio.workspace = true

[dev-dependencies]
grim-testkit.workspace = true
