[package]
name = "grim-world"
description = "Level geometry: BSP queries, collision traces and zones"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
web-time.workspace = true
grim-package.workspace = true
grim-assets.workspace = true
grim-render.workspace = true

[dev-dependencies]
grim-object.workspace = true
grim-testkit.workspace = true
